---
ntp: "chrony"
ntp_service: "chronyd"
epel_repo_rpm: "https://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-9.noarch.rpm"
postgres: "postgresql-server"
postgres_service: "postgresql"
ansible_postgres_deps:
  - python-psycopg2
