- hosts: localhost
  gather_facts: no
  vars_prompt:
  - name: target_host
    prompt: target hostname or IP
    private: no
  tasks:
    - add_host:
        name: "{{ target_host }}"
        groups: hostlist
        ansible_python_interpreter: "/usr/bin/python3"

- name: deploy
  hosts: hostlist
  remote_user: root
  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible (Ubuntu)
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      register: output
      changed_when: output.stdout != ""
    - setup:
  roles:
    - role: base
      firewall_exceptions:
        - "http"
        - "https"
