---
lets_encrypt_pub_key: "/etc/letsencrypt/live/{{inventory_hostname}}/fullchain.pem"
lets_encrypt_priv_key: "/etc/letsencrypt/live/{{inventory_hostname}}/privkey.pem"
oval_environment: "PRD"
slack_channel: "#ops"
slack_oauth_api_token: "{{vault_slack_oauth_api_token}}"
ssh_keys:
  - jyundt-id_rsa.pub
  - jheffner-id_rsa.pub
slack_ansible_api_token: "{{vault_slack_ansible_api_token}}"
certbot_username: "{{vault_certbot_username}}"
postgres_version: "9.6"
postgres_version_no_dot: "{{postgres_version|regex_replace('[.]', '')}}"
db_user: "{{vault_db_user}}"
db_pass: "{{vault_db_pass}}"
db_name: "{{vault_db_name}}"
#We are also using the first host in the DB group (assuming there is only one)
db_host: "{{groups['db'][0]}}"
ssl_cipher_suite: "ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5:!DSS"
oval_user: "oval" 
oval_uid: "1050" 
oval_group: "oval"
oval_gid: "1050" 
oval_homedir: "/home/{{oval_user}}"
oval_user_shell: "/bin/bash"
app_server_port: 5000
app_dir: "{{oval_homedir}}/oval"
venv_dir: "{{app_dir}}/venv"
oval_vars: "{{oval_homedir}}/.oval_vars"
git_repo: "https://github.com/jyundt/oval.git"
git_branch: "release"
google_analytics_id: "{{vault_google_analytics_id[oval_environment]}}"
flask_secret_key: "{{vault_flask_secret_key}}"
mail_password: "{{vault_mail_password}}"
mail_subject_prefix:
    TST: TheOval_TST
    PRD: The_Oval
    DEV: TheOval_DEV
disqus_id:
    TST: the-oval-tst
    DEV: the-oval-dev
    PRD: theoval
mail_username: "{{vault_mail_username}}"
strava_api_token: "{{vault_strava_api_token[oval_environment]}}"
strava_client_secret: "{{vault_strava_client_secret[oval_environment]}}"
strava_client_id: "{{vault_strava_client_id[oval_environment]}}"
pip_version: "9.0.1"
python_version: "python2.7"
aws_access_key: "{{vault_aws_access_key}}"
aws_secret_key: "{{vault_aws_secret_key}}"
aws_public_hosted_zone_id: "{{vault_aws_public_hosted_zone_id}}"
aws_private_hosted_zone_id: "{{vault_aws_private_hosted_zone_id}}"
s3_aws_access_key: "{{vault_s3_aws_access_key}}"
s3_aws_secret_key: "{{vault_s3_aws_secret_key}}"
s3_db_bucket_name: "{{vault_s3_db_bucket_name}}"
s3_attachments_bucket_name: "{{vault_s3_attachments_bucket_name}}"
dns_zone: "theoval.us"
