---
- name: Restart postgres
  service: 
    name: "{{postgres_service}}"
    state: restarted

- name: Restart sshd
  service:
    name: sshd
    state: restarted

- name: Restart app server
  service:
    name: "{{app_server}}" 
    state: restarted

- name: Upgrade DB schema
  shell: "source /home/{{oval_user}}/.bashrc ; . {{venv_dir}}/bin/activate &&  {{app_dir}}/manage.py db upgrade"
  args:
    chdir: "{{app_dir}}"
  become: true
  become_user: "{{oval_user}}"

- name: Restart nginx
  service:
    name: nginx
    state: restarted
